# Generated by Django 5.2.6 on 2025-12-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.IntegerField(blank=True, unique=True)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('adhaar', models.CharField(max_length=16, unique=True)),
            ],
        ),
    ]
