# Generated by Django 5.2.6 on 2026-01-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=5, unique=True)),
                ('state_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uc_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uc_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('founded_by', models.CharField(max_length=100)),
                ('founded_year', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=50, unique=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gender')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.qualification')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.state')),
                ('university_college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.university')),
            ],
        ),
    ]
