# Generated by Django 5.2.6 on 2026-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
